# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDoubleSpinBox, QFrame,
    QGridLayout, QHBoxLayout, QLabel, QLayout,
    QLineEdit, QMainWindow, QPlainTextEdit, QPushButton,
    QRadioButton, QSizePolicy, QSlider, QSpinBox,
    QTabWidget, QToolButton, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1000, 800)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 1000, 800))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMaximumSize(QSize(1000, 800))
        self.tabWidget.setUsesScrollButtons(False)
        self.tab_main = QWidget()
        self.tab_main.setObjectName(u"tab_main")
        self.frame_AxisSliders = QFrame(self.tab_main)
        self.frame_AxisSliders.setObjectName(u"frame_AxisSliders")
        self.frame_AxisSliders.setGeometry(QRect(230, 10, 741, 241))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.frame_AxisSliders.sizePolicy().hasHeightForWidth())
        self.frame_AxisSliders.setSizePolicy(sizePolicy1)
        self.frame_AxisSliders.setMaximumSize(QSize(16777215, 16777215))
        self.frame_AxisSliders.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_AxisSliders.setFrameShadow(QFrame.Shadow.Raised)
        self.layoutWidget = QWidget(self.frame_AxisSliders)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(10, 10, 721, 221))
        self.gridLayout = QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.frame_6 = QFrame(self.layoutWidget)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QFrame.Shadow.Plain)
        self.Axis1 = QSpinBox(self.frame_6)
        self.Axis1.setObjectName(u"Axis1")
        self.Axis1.setGeometry(QRect(10, 30, 61, 31))
        sizePolicy1.setHeightForWidth(self.Axis1.sizePolicy().hasHeightForWidth())
        self.Axis1.setSizePolicy(sizePolicy1)
        self.Axis1.setMaximumSize(QSize(200, 16777215))
        self.Axis1.setMinimum(-180)
        self.Axis1.setMaximum(180)
        self.Axis1Label = QLabel(self.frame_6)
        self.Axis1Label.setObjectName(u"Axis1Label")
        self.Axis1Label.setGeometry(QRect(20, 10, 47, 13))
        font = QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.Axis1Label.setFont(font)
        self.Axis1Slider = QSlider(self.frame_6)
        self.Axis1Slider.setObjectName(u"Axis1Slider")
        self.Axis1Slider.setGeometry(QRect(90, 30, 250, 31))
        self.Axis1Slider.setMinimum(-180)
        self.Axis1Slider.setMaximum(180)
        self.Axis1Slider.setSingleStep(1)
        self.Axis1Slider.setOrientation(Qt.Orientation.Horizontal)
        self.Axis1Slider.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.Axis1Slider.setTickInterval(30)

        self.verticalLayout_2.addWidget(self.frame_6)

        self.frame_7 = QFrame(self.layoutWidget)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QFrame.Shadow.Plain)
        self.Axis2 = QSpinBox(self.frame_7)
        self.Axis2.setObjectName(u"Axis2")
        self.Axis2.setGeometry(QRect(10, 30, 61, 31))
        sizePolicy1.setHeightForWidth(self.Axis2.sizePolicy().hasHeightForWidth())
        self.Axis2.setSizePolicy(sizePolicy1)
        self.Axis2.setMaximumSize(QSize(200, 16777215))
        self.Axis2.setMinimum(-90)
        self.Axis2.setMaximum(90)
        self.Axis2Label = QLabel(self.frame_7)
        self.Axis2Label.setObjectName(u"Axis2Label")
        self.Axis2Label.setGeometry(QRect(20, 10, 47, 13))
        self.Axis2Label.setFont(font)
        self.Axis2Slider = QSlider(self.frame_7)
        self.Axis2Slider.setObjectName(u"Axis2Slider")
        self.Axis2Slider.setGeometry(QRect(90, 30, 250, 31))
        self.Axis2Slider.setMinimum(-90)
        self.Axis2Slider.setMaximum(90)
        self.Axis2Slider.setOrientation(Qt.Orientation.Horizontal)
        self.Axis2Slider.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.Axis2Slider.setTickInterval(20)

        self.verticalLayout_2.addWidget(self.frame_7)

        self.frame_8 = QFrame(self.layoutWidget)
        self.frame_8.setObjectName(u"frame_8")
        self.frame_8.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QFrame.Shadow.Plain)
        self.Axis3 = QSpinBox(self.frame_8)
        self.Axis3.setObjectName(u"Axis3")
        self.Axis3.setGeometry(QRect(10, 30, 61, 31))
        sizePolicy1.setHeightForWidth(self.Axis3.sizePolicy().hasHeightForWidth())
        self.Axis3.setSizePolicy(sizePolicy1)
        self.Axis3.setMaximumSize(QSize(200, 16777215))
        self.Axis3.setMinimum(-165)
        self.Axis3.setMaximum(165)
        self.Axis3Label = QLabel(self.frame_8)
        self.Axis3Label.setObjectName(u"Axis3Label")
        self.Axis3Label.setGeometry(QRect(20, 10, 47, 13))
        self.Axis3Label.setFont(font)
        self.Axis3Slider = QSlider(self.frame_8)
        self.Axis3Slider.setObjectName(u"Axis3Slider")
        self.Axis3Slider.setGeometry(QRect(90, 30, 250, 31))
        self.Axis3Slider.setMinimum(-165)
        self.Axis3Slider.setMaximum(165)
        self.Axis3Slider.setOrientation(Qt.Orientation.Horizontal)
        self.Axis3Slider.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.Axis3Slider.setTickInterval(20)

        self.verticalLayout_2.addWidget(self.frame_8)


        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)

        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.frame_9 = QFrame(self.layoutWidget)
        self.frame_9.setObjectName(u"frame_9")
        self.frame_9.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QFrame.Shadow.Plain)
        self.Axis4 = QSpinBox(self.frame_9)
        self.Axis4.setObjectName(u"Axis4")
        self.Axis4.setGeometry(QRect(10, 30, 61, 31))
        sizePolicy1.setHeightForWidth(self.Axis4.sizePolicy().hasHeightForWidth())
        self.Axis4.setSizePolicy(sizePolicy1)
        self.Axis4.setMaximumSize(QSize(200, 16777215))
        self.Axis4.setMinimum(-360)
        self.Axis4.setMaximum(360)
        self.Axis4Label = QLabel(self.frame_9)
        self.Axis4Label.setObjectName(u"Axis4Label")
        self.Axis4Label.setGeometry(QRect(20, 10, 47, 13))
        self.Axis4Label.setFont(font)
        self.Axis4Slider = QSlider(self.frame_9)
        self.Axis4Slider.setObjectName(u"Axis4Slider")
        self.Axis4Slider.setGeometry(QRect(90, 30, 250, 31))
        self.Axis4Slider.setMinimum(-360)
        self.Axis4Slider.setMaximum(360)
        self.Axis4Slider.setOrientation(Qt.Orientation.Horizontal)
        self.Axis4Slider.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.Axis4Slider.setTickInterval(30)

        self.verticalLayout.addWidget(self.frame_9)

        self.frame_10 = QFrame(self.layoutWidget)
        self.frame_10.setObjectName(u"frame_10")
        self.frame_10.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QFrame.Shadow.Plain)
        self.Axis5 = QSpinBox(self.frame_10)
        self.Axis5.setObjectName(u"Axis5")
        self.Axis5.setGeometry(QRect(10, 30, 61, 31))
        sizePolicy1.setHeightForWidth(self.Axis5.sizePolicy().hasHeightForWidth())
        self.Axis5.setSizePolicy(sizePolicy1)
        self.Axis5.setMaximumSize(QSize(200, 16777215))
        self.Axis5.setMinimum(-165)
        self.Axis5.setMaximum(165)
        self.Axis5Label = QLabel(self.frame_10)
        self.Axis5Label.setObjectName(u"Axis5Label")
        self.Axis5Label.setGeometry(QRect(20, 10, 47, 13))
        self.Axis5Label.setFont(font)
        self.Axis5Slider = QSlider(self.frame_10)
        self.Axis5Slider.setObjectName(u"Axis5Slider")
        self.Axis5Slider.setGeometry(QRect(90, 30, 250, 31))
        self.Axis5Slider.setMinimum(-165)
        self.Axis5Slider.setMaximum(165)
        self.Axis5Slider.setOrientation(Qt.Orientation.Horizontal)
        self.Axis5Slider.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.Axis5Slider.setTickInterval(20)

        self.verticalLayout.addWidget(self.frame_10)

        self.frame_11 = QFrame(self.layoutWidget)
        self.frame_11.setObjectName(u"frame_11")
        self.frame_11.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QFrame.Shadow.Plain)
        self.Axis6 = QSpinBox(self.frame_11)
        self.Axis6.setObjectName(u"Axis6")
        self.Axis6.setGeometry(QRect(10, 30, 61, 31))
        sizePolicy1.setHeightForWidth(self.Axis6.sizePolicy().hasHeightForWidth())
        self.Axis6.setSizePolicy(sizePolicy1)
        self.Axis6.setMaximumSize(QSize(200, 16777215))
        self.Axis6.setMinimum(-360)
        self.Axis6.setMaximum(360)
        self.Axis6Label = QLabel(self.frame_11)
        self.Axis6Label.setObjectName(u"Axis6Label")
        self.Axis6Label.setGeometry(QRect(20, 10, 47, 13))
        self.Axis6Label.setFont(font)
        self.Axis6Slider = QSlider(self.frame_11)
        self.Axis6Slider.setObjectName(u"Axis6Slider")
        self.Axis6Slider.setGeometry(QRect(90, 30, 250, 31))
        self.Axis6Slider.setMinimum(-360)
        self.Axis6Slider.setMaximum(360)
        self.Axis6Slider.setOrientation(Qt.Orientation.Horizontal)
        self.Axis6Slider.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.Axis6Slider.setTickInterval(30)

        self.verticalLayout.addWidget(self.frame_11)


        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)

        self.frame_JogSwitch = QFrame(self.tab_main)
        self.frame_JogSwitch.setObjectName(u"frame_JogSwitch")
        self.frame_JogSwitch.setGeometry(QRect(10, 20, 205, 70))
        self.frame_JogSwitch.setFrameShape(QFrame.Shape.Box)
        self.frame_JogSwitch.setFrameShadow(QFrame.Shadow.Raised)
        self.gridLayout_2 = QGridLayout(self.frame_JogSwitch)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.TrajectoryMotionButton = QRadioButton(self.frame_JogSwitch)
        self.TrajectoryMotionButton.setObjectName(u"TrajectoryMotionButton")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Maximum)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.TrajectoryMotionButton.sizePolicy().hasHeightForWidth())
        self.TrajectoryMotionButton.setSizePolicy(sizePolicy2)
        font1 = QFont()
        font1.setPointSize(9)
        self.TrajectoryMotionButton.setFont(font1)

        self.gridLayout_2.addWidget(self.TrajectoryMotionButton, 1, 1, 1, 1)

        self.MotionType_label = QLabel(self.frame_JogSwitch)
        self.MotionType_label.setObjectName(u"MotionType_label")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Maximum)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.MotionType_label.sizePolicy().hasHeightForWidth())
        self.MotionType_label.setSizePolicy(sizePolicy3)
        self.MotionType_label.setFont(font)
        self.MotionType_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout_2.addWidget(self.MotionType_label, 0, 0, 1, 1)

        self.JointJogButton = QRadioButton(self.frame_JogSwitch)
        self.JointJogButton.setObjectName(u"JointJogButton")
        sizePolicy2.setHeightForWidth(self.JointJogButton.sizePolicy().hasHeightForWidth())
        self.JointJogButton.setSizePolicy(sizePolicy2)
        self.JointJogButton.setFont(font1)
        self.JointJogButton.setCheckable(True)
        self.JointJogButton.setChecked(False)

        self.gridLayout_2.addWidget(self.JointJogButton, 1, 0, 1, 1)

        self.frame_CartesianCoordinates = QFrame(self.tab_main)
        self.frame_CartesianCoordinates.setObjectName(u"frame_CartesianCoordinates")
        self.frame_CartesianCoordinates.setGeometry(QRect(290, 260, 651, 81))
        self.frame_CartesianCoordinates.setFrameShape(QFrame.Shape.Box)
        self.frame_CartesianCoordinates.setFrameShadow(QFrame.Shadow.Raised)
        self.layoutWidget1 = QWidget(self.frame_CartesianCoordinates)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.layoutWidget1.setGeometry(QRect(560, 10, 81, 61))
        self.cart_Rz_layout = QVBoxLayout(self.layoutWidget1)
        self.cart_Rz_layout.setObjectName(u"cart_Rz_layout")
        self.cart_Rz_layout.setContentsMargins(0, 0, 0, 0)
        self.cart_Rz_SpinBox_label = QLabel(self.layoutWidget1)
        self.cart_Rz_SpinBox_label.setObjectName(u"cart_Rz_SpinBox_label")
        font2 = QFont()
        font2.setPointSize(12)
        font2.setBold(True)
        self.cart_Rz_SpinBox_label.setFont(font2)
        self.cart_Rz_SpinBox_label.setFrameShadow(QFrame.Shadow.Plain)
        self.cart_Rz_SpinBox_label.setTextFormat(Qt.TextFormat.PlainText)
        self.cart_Rz_SpinBox_label.setScaledContents(True)
        self.cart_Rz_SpinBox_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.cart_Rz_layout.addWidget(self.cart_Rz_SpinBox_label)

        self.cart_Rz_SpinBox = QSpinBox(self.layoutWidget1)
        self.cart_Rz_SpinBox.setObjectName(u"cart_Rz_SpinBox")
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Expanding)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.cart_Rz_SpinBox.sizePolicy().hasHeightForWidth())
        self.cart_Rz_SpinBox.setSizePolicy(sizePolicy4)
        self.cart_Rz_SpinBox.setMaximumSize(QSize(200, 16777215))
        self.cart_Rz_SpinBox.setMinimum(-180)
        self.cart_Rz_SpinBox.setMaximum(180)

        self.cart_Rz_layout.addWidget(self.cart_Rz_SpinBox)

        self.layoutWidget2 = QWidget(self.frame_CartesianCoordinates)
        self.layoutWidget2.setObjectName(u"layoutWidget2")
        self.layoutWidget2.setGeometry(QRect(120, 10, 81, 61))
        self.cart_Y_layout = QVBoxLayout(self.layoutWidget2)
        self.cart_Y_layout.setObjectName(u"cart_Y_layout")
        self.cart_Y_layout.setContentsMargins(0, 0, 0, 0)
        self.cart_Y_doubleSpinBox_label = QLabel(self.layoutWidget2)
        self.cart_Y_doubleSpinBox_label.setObjectName(u"cart_Y_doubleSpinBox_label")
        self.cart_Y_doubleSpinBox_label.setFont(font2)
        self.cart_Y_doubleSpinBox_label.setFrameShadow(QFrame.Shadow.Plain)
        self.cart_Y_doubleSpinBox_label.setTextFormat(Qt.TextFormat.PlainText)
        self.cart_Y_doubleSpinBox_label.setScaledContents(True)
        self.cart_Y_doubleSpinBox_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.cart_Y_layout.addWidget(self.cart_Y_doubleSpinBox_label)

        self.cart_Y_doubleSpinBox = QDoubleSpinBox(self.layoutWidget2)
        self.cart_Y_doubleSpinBox.setObjectName(u"cart_Y_doubleSpinBox")
        sizePolicy5 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.cart_Y_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.cart_Y_doubleSpinBox.setSizePolicy(sizePolicy5)
        self.cart_Y_doubleSpinBox.setDecimals(1)
        self.cart_Y_doubleSpinBox.setMinimum(-2000.000000000000000)
        self.cart_Y_doubleSpinBox.setMaximum(2000.000000000000000)

        self.cart_Y_layout.addWidget(self.cart_Y_doubleSpinBox)

        self.layoutWidget3 = QWidget(self.frame_CartesianCoordinates)
        self.layoutWidget3.setObjectName(u"layoutWidget3")
        self.layoutWidget3.setGeometry(QRect(230, 10, 81, 61))
        self.cart_Z_layout = QVBoxLayout(self.layoutWidget3)
        self.cart_Z_layout.setObjectName(u"cart_Z_layout")
        self.cart_Z_layout.setContentsMargins(0, 0, 0, 0)
        self.cart_Z_doubleSpinBox_label = QLabel(self.layoutWidget3)
        self.cart_Z_doubleSpinBox_label.setObjectName(u"cart_Z_doubleSpinBox_label")
        self.cart_Z_doubleSpinBox_label.setFont(font2)
        self.cart_Z_doubleSpinBox_label.setFrameShadow(QFrame.Shadow.Plain)
        self.cart_Z_doubleSpinBox_label.setTextFormat(Qt.TextFormat.PlainText)
        self.cart_Z_doubleSpinBox_label.setScaledContents(True)
        self.cart_Z_doubleSpinBox_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.cart_Z_layout.addWidget(self.cart_Z_doubleSpinBox_label)

        self.cart_Z_doubleSpinBox = QDoubleSpinBox(self.layoutWidget3)
        self.cart_Z_doubleSpinBox.setObjectName(u"cart_Z_doubleSpinBox")
        sizePolicy5.setHeightForWidth(self.cart_Z_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.cart_Z_doubleSpinBox.setSizePolicy(sizePolicy5)
        self.cart_Z_doubleSpinBox.setDecimals(1)
        self.cart_Z_doubleSpinBox.setMinimum(-2000.000000000000000)
        self.cart_Z_doubleSpinBox.setMaximum(2000.000000000000000)

        self.cart_Z_layout.addWidget(self.cart_Z_doubleSpinBox)

        self.layoutWidget4 = QWidget(self.frame_CartesianCoordinates)
        self.layoutWidget4.setObjectName(u"layoutWidget4")
        self.layoutWidget4.setGeometry(QRect(10, 10, 81, 61))
        self.cart_X_layout = QVBoxLayout(self.layoutWidget4)
        self.cart_X_layout.setObjectName(u"cart_X_layout")
        self.cart_X_layout.setContentsMargins(0, 0, 0, 0)
        self.cart_X_doubleSpinBox_label = QLabel(self.layoutWidget4)
        self.cart_X_doubleSpinBox_label.setObjectName(u"cart_X_doubleSpinBox_label")
        self.cart_X_doubleSpinBox_label.setFont(font2)
        self.cart_X_doubleSpinBox_label.setFrameShadow(QFrame.Shadow.Plain)
        self.cart_X_doubleSpinBox_label.setTextFormat(Qt.TextFormat.PlainText)
        self.cart_X_doubleSpinBox_label.setScaledContents(True)
        self.cart_X_doubleSpinBox_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.cart_X_layout.addWidget(self.cart_X_doubleSpinBox_label)

        self.cart_X_doubleSpinBox = QDoubleSpinBox(self.layoutWidget4)
        self.cart_X_doubleSpinBox.setObjectName(u"cart_X_doubleSpinBox")
        sizePolicy5.setHeightForWidth(self.cart_X_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.cart_X_doubleSpinBox.setSizePolicy(sizePolicy5)
        self.cart_X_doubleSpinBox.setDecimals(1)
        self.cart_X_doubleSpinBox.setMinimum(-2000.000000000000000)
        self.cart_X_doubleSpinBox.setMaximum(2000.000000000000000)

        self.cart_X_layout.addWidget(self.cart_X_doubleSpinBox)

        self.layoutWidget5 = QWidget(self.frame_CartesianCoordinates)
        self.layoutWidget5.setObjectName(u"layoutWidget5")
        self.layoutWidget5.setGeometry(QRect(340, 10, 81, 61))
        self.cart_Rx_layout = QVBoxLayout(self.layoutWidget5)
        self.cart_Rx_layout.setObjectName(u"cart_Rx_layout")
        self.cart_Rx_layout.setContentsMargins(0, 0, 0, 0)
        self.cart_Rx_SpinBox_label = QLabel(self.layoutWidget5)
        self.cart_Rx_SpinBox_label.setObjectName(u"cart_Rx_SpinBox_label")
        self.cart_Rx_SpinBox_label.setFont(font2)
        self.cart_Rx_SpinBox_label.setFrameShadow(QFrame.Shadow.Plain)
        self.cart_Rx_SpinBox_label.setTextFormat(Qt.TextFormat.PlainText)
        self.cart_Rx_SpinBox_label.setScaledContents(True)
        self.cart_Rx_SpinBox_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.cart_Rx_layout.addWidget(self.cart_Rx_SpinBox_label)

        self.cart_Rx_SpinBox = QSpinBox(self.layoutWidget5)
        self.cart_Rx_SpinBox.setObjectName(u"cart_Rx_SpinBox")
        sizePolicy4.setHeightForWidth(self.cart_Rx_SpinBox.sizePolicy().hasHeightForWidth())
        self.cart_Rx_SpinBox.setSizePolicy(sizePolicy4)
        self.cart_Rx_SpinBox.setMaximumSize(QSize(200, 16777215))
        font3 = QFont()
        font3.setPointSize(8)
        self.cart_Rx_SpinBox.setFont(font3)
        self.cart_Rx_SpinBox.setMinimum(-180)
        self.cart_Rx_SpinBox.setMaximum(180)

        self.cart_Rx_layout.addWidget(self.cart_Rx_SpinBox)

        self.layoutWidget6 = QWidget(self.frame_CartesianCoordinates)
        self.layoutWidget6.setObjectName(u"layoutWidget6")
        self.layoutWidget6.setGeometry(QRect(450, 10, 81, 61))
        self.cart_Ry_layout = QVBoxLayout(self.layoutWidget6)
        self.cart_Ry_layout.setObjectName(u"cart_Ry_layout")
        self.cart_Ry_layout.setContentsMargins(0, 0, 0, 0)
        self.cart_Ry_SpinBox_label = QLabel(self.layoutWidget6)
        self.cart_Ry_SpinBox_label.setObjectName(u"cart_Ry_SpinBox_label")
        self.cart_Ry_SpinBox_label.setFont(font2)
        self.cart_Ry_SpinBox_label.setFrameShadow(QFrame.Shadow.Plain)
        self.cart_Ry_SpinBox_label.setTextFormat(Qt.TextFormat.PlainText)
        self.cart_Ry_SpinBox_label.setScaledContents(True)
        self.cart_Ry_SpinBox_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.cart_Ry_layout.addWidget(self.cart_Ry_SpinBox_label)

        self.cart_Ry_SpinBox = QSpinBox(self.layoutWidget6)
        self.cart_Ry_SpinBox.setObjectName(u"cart_Ry_SpinBox")
        sizePolicy4.setHeightForWidth(self.cart_Ry_SpinBox.sizePolicy().hasHeightForWidth())
        self.cart_Ry_SpinBox.setSizePolicy(sizePolicy4)
        self.cart_Ry_SpinBox.setMaximumSize(QSize(200, 16777215))
        self.cart_Ry_SpinBox.setMinimum(-180)
        self.cart_Ry_SpinBox.setMaximum(180)

        self.cart_Ry_layout.addWidget(self.cart_Ry_SpinBox)

        self.SendButton = QPushButton(self.tab_main)
        self.SendButton.setObjectName(u"SendButton")
        self.SendButton.setGeometry(QRect(330, 360, 351, 41))
        font4 = QFont()
        font4.setPointSize(10)
        self.SendButton.setFont(font4)
        self.LaunchButton = QPushButton(self.tab_main)
        self.LaunchButton.setObjectName(u"LaunchButton")
        self.LaunchButton.setGeometry(QRect(40, 210, 161, 41))
        self.LaunchButton.setFont(font4)
        self.layoutWidget7 = QWidget(self.tab_main)
        self.layoutWidget7.setObjectName(u"layoutWidget7")
        self.layoutWidget7.setGeometry(QRect(60, 140, 121, 61))
        self.TrajectoryType_layout = QVBoxLayout(self.layoutWidget7)
        self.TrajectoryType_layout.setObjectName(u"TrajectoryType_layout")
        self.TrajectoryType_layout.setContentsMargins(0, 0, 0, 0)
        self.TrajectoryType_label = QLabel(self.layoutWidget7)
        self.TrajectoryType_label.setObjectName(u"TrajectoryType_label")
        self.TrajectoryType_label.setFont(font)
        self.TrajectoryType_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.TrajectoryType_layout.addWidget(self.TrajectoryType_label)

        self.TrajectoryType_comboBox = QComboBox(self.layoutWidget7)
        self.TrajectoryType_comboBox.addItem("")
        self.TrajectoryType_comboBox.addItem("")
        self.TrajectoryType_comboBox.addItem("")
        self.TrajectoryType_comboBox.setObjectName(u"TrajectoryType_comboBox")
        sizePolicy4.setHeightForWidth(self.TrajectoryType_comboBox.sizePolicy().hasHeightForWidth())
        self.TrajectoryType_comboBox.setSizePolicy(sizePolicy4)
        self.TrajectoryType_comboBox.setFont(font4)

        self.TrajectoryType_layout.addWidget(self.TrajectoryType_comboBox)

        self.ToolPos_frame = QFrame(self.tab_main)
        self.ToolPos_frame.setObjectName(u"ToolPos_frame")
        self.ToolPos_frame.setGeometry(QRect(10, 550, 160, 210))
        self.ToolPos_frame.setFrameShape(QFrame.Shape.Box)
        self.ToolPos_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.gridLayout_4 = QGridLayout(self.ToolPos_frame)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.toolCoord_layout = QVBoxLayout()
        self.toolCoord_layout.setObjectName(u"toolCoord_layout")
        self.toolCoordX_label = QLabel(self.ToolPos_frame)
        self.toolCoordX_label.setObjectName(u"toolCoordX_label")
        sizePolicy6 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Preferred)
        sizePolicy6.setHorizontalStretch(0)
        sizePolicy6.setVerticalStretch(0)
        sizePolicy6.setHeightForWidth(self.toolCoordX_label.sizePolicy().hasHeightForWidth())
        self.toolCoordX_label.setSizePolicy(sizePolicy6)
        font5 = QFont()
        font5.setPointSize(11)
        self.toolCoordX_label.setFont(font5)
        self.toolCoordX_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.toolCoord_layout.addWidget(self.toolCoordX_label)

        self.toolCoordY_label = QLabel(self.ToolPos_frame)
        self.toolCoordY_label.setObjectName(u"toolCoordY_label")
        sizePolicy6.setHeightForWidth(self.toolCoordY_label.sizePolicy().hasHeightForWidth())
        self.toolCoordY_label.setSizePolicy(sizePolicy6)
        self.toolCoordY_label.setFont(font5)
        self.toolCoordY_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.toolCoord_layout.addWidget(self.toolCoordY_label)

        self.toolCoordZ_label = QLabel(self.ToolPos_frame)
        self.toolCoordZ_label.setObjectName(u"toolCoordZ_label")
        sizePolicy6.setHeightForWidth(self.toolCoordZ_label.sizePolicy().hasHeightForWidth())
        self.toolCoordZ_label.setSizePolicy(sizePolicy6)
        self.toolCoordZ_label.setFont(font5)
        self.toolCoordZ_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.toolCoord_layout.addWidget(self.toolCoordZ_label)

        self.toolCoordRx_label = QLabel(self.ToolPos_frame)
        self.toolCoordRx_label.setObjectName(u"toolCoordRx_label")
        sizePolicy6.setHeightForWidth(self.toolCoordRx_label.sizePolicy().hasHeightForWidth())
        self.toolCoordRx_label.setSizePolicy(sizePolicy6)
        self.toolCoordRx_label.setFont(font5)
        self.toolCoordRx_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.toolCoord_layout.addWidget(self.toolCoordRx_label)

        self.toolCoordRy_label = QLabel(self.ToolPos_frame)
        self.toolCoordRy_label.setObjectName(u"toolCoordRy_label")
        sizePolicy6.setHeightForWidth(self.toolCoordRy_label.sizePolicy().hasHeightForWidth())
        self.toolCoordRy_label.setSizePolicy(sizePolicy6)
        self.toolCoordRy_label.setFont(font5)
        self.toolCoordRy_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.toolCoord_layout.addWidget(self.toolCoordRy_label)

        self.toolCoordRz_label = QLabel(self.ToolPos_frame)
        self.toolCoordRz_label.setObjectName(u"toolCoordRz_label")
        sizePolicy6.setHeightForWidth(self.toolCoordRz_label.sizePolicy().hasHeightForWidth())
        self.toolCoordRz_label.setSizePolicy(sizePolicy6)
        self.toolCoordRz_label.setFont(font5)
        self.toolCoordRz_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.toolCoord_layout.addWidget(self.toolCoordRz_label)


        self.gridLayout_4.addLayout(self.toolCoord_layout, 1, 1, 1, 1)

        self.posLabel_layout = QVBoxLayout()
        self.posLabel_layout.setObjectName(u"posLabel_layout")
        self.posLabel_layout.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.posX_label = QLabel(self.ToolPos_frame)
        self.posX_label.setObjectName(u"posX_label")
        sizePolicy7 = QSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Preferred)
        sizePolicy7.setHorizontalStretch(0)
        sizePolicy7.setVerticalStretch(0)
        sizePolicy7.setHeightForWidth(self.posX_label.sizePolicy().hasHeightForWidth())
        self.posX_label.setSizePolicy(sizePolicy7)
        self.posX_label.setFont(font4)
        self.posX_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.posLabel_layout.addWidget(self.posX_label)

        self.posY_label = QLabel(self.ToolPos_frame)
        self.posY_label.setObjectName(u"posY_label")
        sizePolicy7.setHeightForWidth(self.posY_label.sizePolicy().hasHeightForWidth())
        self.posY_label.setSizePolicy(sizePolicy7)
        self.posY_label.setFont(font4)
        self.posY_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.posLabel_layout.addWidget(self.posY_label)

        self.posZ_label = QLabel(self.ToolPos_frame)
        self.posZ_label.setObjectName(u"posZ_label")
        sizePolicy7.setHeightForWidth(self.posZ_label.sizePolicy().hasHeightForWidth())
        self.posZ_label.setSizePolicy(sizePolicy7)
        self.posZ_label.setFont(font4)
        self.posZ_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.posLabel_layout.addWidget(self.posZ_label)

        self.posRx_label = QLabel(self.ToolPos_frame)
        self.posRx_label.setObjectName(u"posRx_label")
        sizePolicy7.setHeightForWidth(self.posRx_label.sizePolicy().hasHeightForWidth())
        self.posRx_label.setSizePolicy(sizePolicy7)
        self.posRx_label.setFont(font4)
        self.posRx_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.posLabel_layout.addWidget(self.posRx_label)

        self.posRy_label = QLabel(self.ToolPos_frame)
        self.posRy_label.setObjectName(u"posRy_label")
        sizePolicy7.setHeightForWidth(self.posRy_label.sizePolicy().hasHeightForWidth())
        self.posRy_label.setSizePolicy(sizePolicy7)
        self.posRy_label.setFont(font4)
        self.posRy_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.posLabel_layout.addWidget(self.posRy_label)

        self.posRz_label = QLabel(self.ToolPos_frame)
        self.posRz_label.setObjectName(u"posRz_label")
        sizePolicy7.setHeightForWidth(self.posRz_label.sizePolicy().hasHeightForWidth())
        self.posRz_label.setSizePolicy(sizePolicy7)
        self.posRz_label.setFont(font4)
        self.posRz_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.posLabel_layout.addWidget(self.posRz_label)


        self.gridLayout_4.addLayout(self.posLabel_layout, 1, 0, 1, 1)

        self.ToolPosition_label = QLabel(self.ToolPos_frame)
        self.ToolPosition_label.setObjectName(u"ToolPosition_label")
        sizePolicy3.setHeightForWidth(self.ToolPosition_label.sizePolicy().hasHeightForWidth())
        self.ToolPosition_label.setSizePolicy(sizePolicy3)
        self.ToolPosition_label.setFont(font)
        self.ToolPosition_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout_4.addWidget(self.ToolPosition_label, 0, 0, 1, 2)

        self.JointAngle_frame = QFrame(self.tab_main)
        self.JointAngle_frame.setObjectName(u"JointAngle_frame")
        self.JointAngle_frame.setGeometry(QRect(210, 550, 160, 210))
        self.JointAngle_frame.setFrameShape(QFrame.Shape.Box)
        self.JointAngle_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.gridLayout_5 = QGridLayout(self.JointAngle_frame)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.JointAngles_label = QLabel(self.JointAngle_frame)
        self.JointAngles_label.setObjectName(u"JointAngles_label")
        sizePolicy3.setHeightForWidth(self.JointAngles_label.sizePolicy().hasHeightForWidth())
        self.JointAngles_label.setSizePolicy(sizePolicy3)
        self.JointAngles_label.setFont(font)
        self.JointAngles_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout_5.addWidget(self.JointAngles_label, 0, 0, 1, 2)

        self.JointAngles_layout = QVBoxLayout()
        self.JointAngles_layout.setObjectName(u"JointAngles_layout")
        self.JointAngles_layout.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.J1_label = QLabel(self.JointAngle_frame)
        self.J1_label.setObjectName(u"J1_label")
        sizePolicy7.setHeightForWidth(self.J1_label.sizePolicy().hasHeightForWidth())
        self.J1_label.setSizePolicy(sizePolicy7)
        self.J1_label.setFont(font4)
        self.J1_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.JointAngles_layout.addWidget(self.J1_label)

        self.J2_label = QLabel(self.JointAngle_frame)
        self.J2_label.setObjectName(u"J2_label")
        sizePolicy7.setHeightForWidth(self.J2_label.sizePolicy().hasHeightForWidth())
        self.J2_label.setSizePolicy(sizePolicy7)
        self.J2_label.setFont(font4)
        self.J2_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.JointAngles_layout.addWidget(self.J2_label)

        self.J3_label = QLabel(self.JointAngle_frame)
        self.J3_label.setObjectName(u"J3_label")
        sizePolicy7.setHeightForWidth(self.J3_label.sizePolicy().hasHeightForWidth())
        self.J3_label.setSizePolicy(sizePolicy7)
        self.J3_label.setFont(font4)
        self.J3_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.JointAngles_layout.addWidget(self.J3_label)

        self.J4_label = QLabel(self.JointAngle_frame)
        self.J4_label.setObjectName(u"J4_label")
        sizePolicy7.setHeightForWidth(self.J4_label.sizePolicy().hasHeightForWidth())
        self.J4_label.setSizePolicy(sizePolicy7)
        self.J4_label.setFont(font4)
        self.J4_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.JointAngles_layout.addWidget(self.J4_label)

        self.J5_label = QLabel(self.JointAngle_frame)
        self.J5_label.setObjectName(u"J5_label")
        sizePolicy7.setHeightForWidth(self.J5_label.sizePolicy().hasHeightForWidth())
        self.J5_label.setSizePolicy(sizePolicy7)
        self.J5_label.setFont(font4)
        self.J5_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.JointAngles_layout.addWidget(self.J5_label)

        self.J6_label = QLabel(self.JointAngle_frame)
        self.J6_label.setObjectName(u"J6_label")
        sizePolicy7.setHeightForWidth(self.J6_label.sizePolicy().hasHeightForWidth())
        self.J6_label.setSizePolicy(sizePolicy7)
        self.J6_label.setFont(font4)
        self.J6_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.JointAngles_layout.addWidget(self.J6_label)


        self.gridLayout_5.addLayout(self.JointAngles_layout, 1, 0, 1, 1)

        self.JointTheta_layout = QVBoxLayout()
        self.JointTheta_layout.setObjectName(u"JointTheta_layout")
        self.Joint1Angle_label = QLabel(self.JointAngle_frame)
        self.Joint1Angle_label.setObjectName(u"Joint1Angle_label")
        sizePolicy6.setHeightForWidth(self.Joint1Angle_label.sizePolicy().hasHeightForWidth())
        self.Joint1Angle_label.setSizePolicy(sizePolicy6)
        self.Joint1Angle_label.setFont(font5)
        self.Joint1Angle_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.JointTheta_layout.addWidget(self.Joint1Angle_label)

        self.Joint2Angle_label = QLabel(self.JointAngle_frame)
        self.Joint2Angle_label.setObjectName(u"Joint2Angle_label")
        sizePolicy6.setHeightForWidth(self.Joint2Angle_label.sizePolicy().hasHeightForWidth())
        self.Joint2Angle_label.setSizePolicy(sizePolicy6)
        self.Joint2Angle_label.setFont(font5)
        self.Joint2Angle_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.JointTheta_layout.addWidget(self.Joint2Angle_label)

        self.Joint3Angle_label = QLabel(self.JointAngle_frame)
        self.Joint3Angle_label.setObjectName(u"Joint3Angle_label")
        sizePolicy6.setHeightForWidth(self.Joint3Angle_label.sizePolicy().hasHeightForWidth())
        self.Joint3Angle_label.setSizePolicy(sizePolicy6)
        self.Joint3Angle_label.setFont(font5)
        self.Joint3Angle_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.JointTheta_layout.addWidget(self.Joint3Angle_label)

        self.Joint4Angle_label = QLabel(self.JointAngle_frame)
        self.Joint4Angle_label.setObjectName(u"Joint4Angle_label")
        sizePolicy6.setHeightForWidth(self.Joint4Angle_label.sizePolicy().hasHeightForWidth())
        self.Joint4Angle_label.setSizePolicy(sizePolicy6)
        self.Joint4Angle_label.setFont(font5)
        self.Joint4Angle_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.JointTheta_layout.addWidget(self.Joint4Angle_label)

        self.Joint5Angle_label = QLabel(self.JointAngle_frame)
        self.Joint5Angle_label.setObjectName(u"Joint5Angle_label")
        sizePolicy6.setHeightForWidth(self.Joint5Angle_label.sizePolicy().hasHeightForWidth())
        self.Joint5Angle_label.setSizePolicy(sizePolicy6)
        self.Joint5Angle_label.setFont(font5)
        self.Joint5Angle_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.JointTheta_layout.addWidget(self.Joint5Angle_label)

        self.Joint6Angle_label = QLabel(self.JointAngle_frame)
        self.Joint6Angle_label.setObjectName(u"Joint6Angle_label")
        sizePolicy6.setHeightForWidth(self.Joint6Angle_label.sizePolicy().hasHeightForWidth())
        self.Joint6Angle_label.setSizePolicy(sizePolicy6)
        self.Joint6Angle_label.setFont(font5)
        self.Joint6Angle_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.JointTheta_layout.addWidget(self.Joint6Angle_label)


        self.gridLayout_5.addLayout(self.JointTheta_layout, 1, 1, 1, 1)

        self.HomeButton = QPushButton(self.tab_main)
        self.HomeButton.setObjectName(u"HomeButton")
        self.HomeButton.setGeometry(QRect(760, 360, 161, 41))
        self.HomeButton.setFont(font4)
        self.Velocity_frame = QFrame(self.tab_main)
        self.Velocity_frame.setObjectName(u"Velocity_frame")
        self.Velocity_frame.setGeometry(QRect(10, 480, 361, 50))
        self.Velocity_frame.setFrameShape(QFrame.Shape.Box)
        self.Velocity_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.Velocity_label = QLabel(self.Velocity_frame)
        self.Velocity_label.setObjectName(u"Velocity_label")
        self.Velocity_label.setGeometry(QRect(310, 10, 41, 30))
        sizePolicy8 = QSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Preferred)
        sizePolicy8.setHorizontalStretch(30)
        sizePolicy8.setVerticalStretch(30)
        sizePolicy8.setHeightForWidth(self.Velocity_label.sizePolicy().hasHeightForWidth())
        self.Velocity_label.setSizePolicy(sizePolicy8)
        font6 = QFont()
        font6.setPointSize(12)
        self.Velocity_label.setFont(font6)
        self.Velocity_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.layoutWidget8 = QWidget(self.Velocity_frame)
        self.layoutWidget8.setObjectName(u"layoutWidget8")
        self.layoutWidget8.setGeometry(QRect(11, 11, 291, 29))
        self.horizontalLayout = QHBoxLayout(self.layoutWidget8)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.VelocityTag_label = QLabel(self.layoutWidget8)
        self.VelocityTag_label.setObjectName(u"VelocityTag_label")
        sizePolicy7.setHeightForWidth(self.VelocityTag_label.sizePolicy().hasHeightForWidth())
        self.VelocityTag_label.setSizePolicy(sizePolicy7)
        self.VelocityTag_label.setFont(font)

        self.horizontalLayout.addWidget(self.VelocityTag_label)

        self.Velocity_slider = QSlider(self.layoutWidget8)
        self.Velocity_slider.setObjectName(u"Velocity_slider")
        sizePolicy9 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        sizePolicy9.setHorizontalStretch(0)
        sizePolicy9.setVerticalStretch(0)
        sizePolicy9.setHeightForWidth(self.Velocity_slider.sizePolicy().hasHeightForWidth())
        self.Velocity_slider.setSizePolicy(sizePolicy9)
        self.Velocity_slider.setMinimum(10)
        self.Velocity_slider.setMaximum(100)
        self.Velocity_slider.setOrientation(Qt.Orientation.Horizontal)
        self.Velocity_slider.setTickPosition(QSlider.TickPosition.TicksBelow)
        self.Velocity_slider.setTickInterval(10)

        self.horizontalLayout.addWidget(self.Velocity_slider)

        self.Log_frame = QFrame(self.tab_main)
        self.Log_frame.setObjectName(u"Log_frame")
        self.Log_frame.setGeometry(QRect(409, 419, 571, 341))
        sizePolicy1.setHeightForWidth(self.Log_frame.sizePolicy().hasHeightForWidth())
        self.Log_frame.setSizePolicy(sizePolicy1)
        self.Log_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.Log_frame.setFrameShadow(QFrame.Shadow.Plain)
        self.gridLayout_3 = QGridLayout(self.Log_frame)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.verticalLayout_6 = QVBoxLayout()
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.verticalLayout_5 = QVBoxLayout()
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.ConsoleLabel = QLabel(self.Log_frame)
        self.ConsoleLabel.setObjectName(u"ConsoleLabel")
        self.ConsoleLabel.setFont(font2)
        self.ConsoleLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_5.addWidget(self.ConsoleLabel)

        self.Console = QPlainTextEdit(self.Log_frame)
        self.Console.setObjectName(u"Console")
        sizePolicy10 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.MinimumExpanding)
        sizePolicy10.setHorizontalStretch(0)
        sizePolicy10.setVerticalStretch(0)
        sizePolicy10.setHeightForWidth(self.Console.sizePolicy().hasHeightForWidth())
        self.Console.setSizePolicy(sizePolicy10)
        self.Console.setReadOnly(True)

        self.verticalLayout_5.addWidget(self.Console)


        self.verticalLayout_6.addLayout(self.verticalLayout_5)

        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.ConsoleInput = QLineEdit(self.Log_frame)
        self.ConsoleInput.setObjectName(u"ConsoleInput")
        sizePolicy1.setHeightForWidth(self.ConsoleInput.sizePolicy().hasHeightForWidth())
        self.ConsoleInput.setSizePolicy(sizePolicy1)
        self.ConsoleInput.setMinimumSize(QSize(0, 40))

        self.horizontalLayout_4.addWidget(self.ConsoleInput)

        self.ConsoleSend_button = QToolButton(self.Log_frame)
        self.ConsoleSend_button.setObjectName(u"ConsoleSend_button")
        sizePolicy1.setHeightForWidth(self.ConsoleSend_button.sizePolicy().hasHeightForWidth())
        self.ConsoleSend_button.setSizePolicy(sizePolicy1)
        self.ConsoleSend_button.setMinimumSize(QSize(0, 40))
        self.ConsoleSend_button.setMaximumSize(QSize(100, 16777215))

        self.horizontalLayout_4.addWidget(self.ConsoleSend_button)


        self.verticalLayout_6.addLayout(self.horizontalLayout_4)


        self.gridLayout_3.addLayout(self.verticalLayout_6, 0, 0, 1, 1)

        self.TCP_frame = QFrame(self.tab_main)
        self.TCP_frame.setObjectName(u"TCP_frame")
        self.TCP_frame.setGeometry(QRect(10, 260, 270, 210))
        self.TCP_frame.setFrameShape(QFrame.Shape.Box)
        self.TCP_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_7 = QVBoxLayout(self.TCP_frame)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.verticalLayout_3 = QVBoxLayout()
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.TCP_host_addr_label = QLabel(self.TCP_frame)
        self.TCP_host_addr_label.setObjectName(u"TCP_host_addr_label")
        self.TCP_host_addr_label.setMaximumSize(QSize(16777215, 20))

        self.verticalLayout_3.addWidget(self.TCP_host_addr_label)

        self.TCP_host_addr_lineEdit = QLineEdit(self.TCP_frame)
        self.TCP_host_addr_lineEdit.setObjectName(u"TCP_host_addr_lineEdit")
        sizePolicy.setHeightForWidth(self.TCP_host_addr_lineEdit.sizePolicy().hasHeightForWidth())
        self.TCP_host_addr_lineEdit.setSizePolicy(sizePolicy)

        self.verticalLayout_3.addWidget(self.TCP_host_addr_lineEdit)


        self.verticalLayout_7.addLayout(self.verticalLayout_3)

        self.verticalLayout_4 = QVBoxLayout()
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.TCP_host_port_label = QLabel(self.TCP_frame)
        self.TCP_host_port_label.setObjectName(u"TCP_host_port_label")
        self.TCP_host_port_label.setMaximumSize(QSize(16777215, 20))

        self.verticalLayout_4.addWidget(self.TCP_host_port_label)

        self.TCP_host_port_lineEdit = QLineEdit(self.TCP_frame)
        self.TCP_host_port_lineEdit.setObjectName(u"TCP_host_port_lineEdit")
        sizePolicy.setHeightForWidth(self.TCP_host_port_lineEdit.sizePolicy().hasHeightForWidth())
        self.TCP_host_port_lineEdit.setSizePolicy(sizePolicy)

        self.verticalLayout_4.addWidget(self.TCP_host_port_lineEdit)


        self.verticalLayout_7.addLayout(self.verticalLayout_4)

        self.TCP_Connect_button = QPushButton(self.TCP_frame)
        self.TCP_Connect_button.setObjectName(u"TCP_Connect_button")
        sizePolicy5.setHeightForWidth(self.TCP_Connect_button.sizePolicy().hasHeightForWidth())
        self.TCP_Connect_button.setSizePolicy(sizePolicy5)

        self.verticalLayout_7.addWidget(self.TCP_Connect_button)

        self.frame = QFrame(self.tab_main)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 95, 205, 45))
        self.frame.setFrameShape(QFrame.Shape.Box)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.gridLayout_6 = QGridLayout(self.frame)
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.BorunteSwitch_radioButton = QRadioButton(self.frame)
        self.BorunteSwitch_radioButton.setObjectName(u"BorunteSwitch_radioButton")

        self.gridLayout_6.addWidget(self.BorunteSwitch_radioButton, 0, 0, 1, 1)

        self.SimulatorSwitch_radioButton = QRadioButton(self.frame)
        self.SimulatorSwitch_radioButton.setObjectName(u"SimulatorSwitch_radioButton")

        self.gridLayout_6.addWidget(self.SimulatorSwitch_radioButton, 0, 1, 1, 1)

        self.tabWidget.addTab(self.tab_main, "")
        self.tab_config = QWidget()
        self.tab_config.setObjectName(u"tab_config")
        self.LangChange_comboBox = QComboBox(self.tab_config)
        self.LangChange_comboBox.addItem("")
        self.LangChange_comboBox.addItem("")
        self.LangChange_comboBox.setObjectName(u"LangChange_comboBox")
        self.LangChange_comboBox.setGeometry(QRect(10, 10, 121, 41))
        self.LangChange_comboBox.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.LangChange_comboBox.setAutoFillBackground(False)
        self.tabWidget.addTab(self.tab_config, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Axis1.valueChanged.connect(self.Axis1Slider.setValue)
        self.Axis2.valueChanged.connect(self.Axis2Slider.setValue)
        self.Axis3.valueChanged.connect(self.Axis3Slider.setValue)
        self.Axis4.valueChanged.connect(self.Axis4Slider.setValue)
        self.Axis5.valueChanged.connect(self.Axis5Slider.setValue)
        self.Axis6.valueChanged.connect(self.Axis6Slider.setValue)
        self.Axis1Slider.valueChanged.connect(self.Axis1.setValue)
        self.Axis2Slider.valueChanged.connect(self.Axis2.setValue)
        self.Axis3Slider.valueChanged.connect(self.Axis3.setValue)
        self.Axis4Slider.valueChanged.connect(self.Axis4.setValue)
        self.Axis5Slider.valueChanged.connect(self.Axis5.setValue)
        self.Axis6Slider.valueChanged.connect(self.Axis6.setValue)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
#if QT_CONFIG(tooltip)
        self.tab_main.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.Axis1.setSuffix(QCoreApplication.translate("MainWindow", u"\u00ba", None))
        self.Axis1.setPrefix("")
        self.Axis1Label.setText(QCoreApplication.translate("MainWindow", u"Axis 1", None))
        self.Axis2.setSuffix(QCoreApplication.translate("MainWindow", u"\u00ba", None))
        self.Axis2Label.setText(QCoreApplication.translate("MainWindow", u"Axis 2", None))
        self.Axis3.setSuffix(QCoreApplication.translate("MainWindow", u"\u00ba", None))
        self.Axis3Label.setText(QCoreApplication.translate("MainWindow", u"Axis 3", None))
        self.Axis4.setSuffix(QCoreApplication.translate("MainWindow", u"\u00ba", None))
        self.Axis4Label.setText(QCoreApplication.translate("MainWindow", u"Axis 4", None))
        self.Axis5.setSuffix(QCoreApplication.translate("MainWindow", u"\u00ba", None))
        self.Axis5Label.setText(QCoreApplication.translate("MainWindow", u"Axis 5", None))
        self.Axis6.setSuffix(QCoreApplication.translate("MainWindow", u"\u00ba", None))
        self.Axis6Label.setText(QCoreApplication.translate("MainWindow", u"Axis 6", None))
        self.TrajectoryMotionButton.setText(QCoreApplication.translate("MainWindow", u"Trajectory", None))
        self.MotionType_label.setText(QCoreApplication.translate("MainWindow", u"Motion type:", None))
        self.JointJogButton.setText(QCoreApplication.translate("MainWindow", u"Joint jog", None))
        self.cart_Rz_SpinBox_label.setText(QCoreApplication.translate("MainWindow", u"Rz", None))
        self.cart_Rz_SpinBox.setSuffix(QCoreApplication.translate("MainWindow", u"\u00ba", None))
        self.cart_Y_doubleSpinBox_label.setText(QCoreApplication.translate("MainWindow", u"Y", None))
        self.cart_Z_doubleSpinBox_label.setText(QCoreApplication.translate("MainWindow", u"Z", None))
        self.cart_X_doubleSpinBox_label.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.cart_Rx_SpinBox_label.setText(QCoreApplication.translate("MainWindow", u"Rx", None))
        self.cart_Rx_SpinBox.setSuffix(QCoreApplication.translate("MainWindow", u"\u00ba", None))
        self.cart_Ry_SpinBox_label.setText(QCoreApplication.translate("MainWindow", u"Ry", None))
        self.cart_Ry_SpinBox.setSuffix(QCoreApplication.translate("MainWindow", u"\u00ba", None))
        self.SendButton.setText(QCoreApplication.translate("MainWindow", u"Send", None))
        self.LaunchButton.setText(QCoreApplication.translate("MainWindow", u"Launch sim", None))
        self.TrajectoryType_label.setText(QCoreApplication.translate("MainWindow", u"Trajectory type", None))
        self.TrajectoryType_comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"jtraj", None))
        self.TrajectoryType_comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"ctraj", None))
        self.TrajectoryType_comboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"mstraj", None))

        self.toolCoordX_label.setText("")
        self.toolCoordY_label.setText("")
        self.toolCoordZ_label.setText("")
        self.toolCoordRx_label.setText("")
        self.toolCoordRy_label.setText("")
        self.toolCoordRz_label.setText("")
        self.posX_label.setText(QCoreApplication.translate("MainWindow", u"X:", None))
        self.posY_label.setText(QCoreApplication.translate("MainWindow", u"Y:", None))
        self.posZ_label.setText(QCoreApplication.translate("MainWindow", u"Z:", None))
        self.posRx_label.setText(QCoreApplication.translate("MainWindow", u"Rx:", None))
        self.posRy_label.setText(QCoreApplication.translate("MainWindow", u"Ry:", None))
        self.posRz_label.setText(QCoreApplication.translate("MainWindow", u"Rz:", None))
        self.ToolPosition_label.setText(QCoreApplication.translate("MainWindow", u"Tool position:", None))
        self.JointAngles_label.setText(QCoreApplication.translate("MainWindow", u"Joint angle:", None))
        self.J1_label.setText(QCoreApplication.translate("MainWindow", u"J1:", None))
        self.J2_label.setText(QCoreApplication.translate("MainWindow", u"J2:", None))
        self.J3_label.setText(QCoreApplication.translate("MainWindow", u"J3:", None))
        self.J4_label.setText(QCoreApplication.translate("MainWindow", u"J4:", None))
        self.J5_label.setText(QCoreApplication.translate("MainWindow", u"J5:", None))
        self.J6_label.setText(QCoreApplication.translate("MainWindow", u"J6:", None))
        self.Joint1Angle_label.setText("")
        self.Joint2Angle_label.setText("")
        self.Joint3Angle_label.setText("")
        self.Joint4Angle_label.setText("")
        self.Joint5Angle_label.setText("")
        self.Joint6Angle_label.setText("")
        self.HomeButton.setText(QCoreApplication.translate("MainWindow", u"Home", None))
        self.Velocity_label.setText("")
        self.VelocityTag_label.setText(QCoreApplication.translate("MainWindow", u"Velocity:", None))
        self.ConsoleLabel.setText(QCoreApplication.translate("MainWindow", u"Log:", None))
        self.ConsoleSend_button.setText(QCoreApplication.translate("MainWindow", u"Send", None))
        self.TCP_host_addr_label.setText(QCoreApplication.translate("MainWindow", u"Remote Host Addr:", None))
        self.TCP_host_addr_lineEdit.setText(QCoreApplication.translate("MainWindow", u"192.168.4.4", None))
        self.TCP_host_port_label.setText(QCoreApplication.translate("MainWindow", u"Remote Host Port:", None))
        self.TCP_host_port_lineEdit.setText(QCoreApplication.translate("MainWindow", u"502", None))
        self.TCP_Connect_button.setText(QCoreApplication.translate("MainWindow", u"Connect", None))
        self.BorunteSwitch_radioButton.setText(QCoreApplication.translate("MainWindow", u"Borunte", None))
        self.SimulatorSwitch_radioButton.setText(QCoreApplication.translate("MainWindow", u"Simulator", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_main), QCoreApplication.translate("MainWindow", u"Movement", None))
        self.LangChange_comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"English", None))
        self.LangChange_comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"\u0420\u0443\u0441\u0438\u044f\u043d\u0441\u043a\u0438\u0439", None))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_config), QCoreApplication.translate("MainWindow", u"Config", None))
    # retranslateUi

